sudo: false

language: groovy

install: ./gradlew assemble -s
script: ./gradlew funcTest check -s -i --continue -Pcompatibility

jdk:
  - oraclejdk7
  - openjdk7
env:
  - PITEST_REGRESSION_TESTS=latestOnly

#Regression tests with different Gradle versions only on JDK 8
matrix:
  include:
    - jdk: oraclejdk8
      env: PITEST_REGRESSION_TESTS=quick

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -fr $HOME/.gradle/caches/transforms-1/transforms-1.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

